INSERT INTO `departments` (`id`, `name_vn`, `name_en`, `description`) VALUES
(1, 'Bộ môn Các hệ thống thông tin', 'Department of Information Systems', NULL),
(2, 'Bộ môn Công nghệ phần mềm', 'Department of Software Engineering', NULL),
(3, 'Bộ môn Khoa học máy tính', 'Department of Computer Science',  NULL),
(4, 'Bộ môn Mạng và truyền thông', 'Department of Communication Networking', NULL),
(5, 'Bộ môn Khoa học và Kỹ thuật tính toán', 'Department of Computing Science and Engineering', NULL),
(6, 'Khoa Công nghệ thông tin', 'Faculty of Information Technology', NULL),
(7, 'Bộ môn Hệ thống viễn thông', 'Department of Network & Communication Systems', NULL),
(8, 'Bộ môn Thông tin vô tuyến', 'Department of Wireless Communications', NULL),
(9, 'Bộ môn Điện tử và Kỹ thuật máy tính', 'Department of Electronics and Computer Engineering', NULL),
(10, 'Bộ môn Vi cơ điện tử và Vi cơ hệ thống', 'Department of Micro-Electro-Mechanical Systems and Micro Systems',NULL),
(21, 'Bộ môn Thủy khí công nghiệp và môi trường', 'Department of Industrial and Environmental Fluid-Mechanics Engineering', 'FEMA-DIEFME'),
(22, 'Bộ môn Hàng không vũ trụ', 'Department of Aerospace Engineering', 'FEMA-DIEFME'),
(23, 'Bộ môn Công nghệ biển và môi trường', 'Department of Marine and Environment Engineering', 'FEMA-DIEFME'),
(24, 'Bộ môn Công nghệ cơ điện tử', 'Department of Mechatronics Engineering', 'FEMA-DIEFME'),
(26, 'Bộ môn Công nghệ quang tử', 'Department of Nanophotonics Technology', NULL),
(27, 'Bộ môn Vật liệu và linh kiện từ tính nano', 'Department of Nano Magnetic Materials and Devices', NULL),
(28, 'Bộ môn Vật liệu và linh kiện bán dẫn nano', 'Department of Nano Semiconductor Materials and Devices', NULL),
(29, 'Bộ môn Công nghệ nano sinh học', 'Department of Nano Biotechnology', NULL);