INSERT INTO `unit_data` (`id`, `unit_level`, `unitname_vn`, `unitname_en`, `parent_units`, `child_units`, `description`) VALUES
(1, '2', 'Bộ môn Các hệ thống thông tin', 'Department of Information Systems', 6, NULL, NULL),
(2, '2', 'Bộ môn Công nghệ phần mềm', 'Department of Software Engineering', 6, NULL, NULL),
(3, '2', 'Bộ môn Khoa học máy tính', 'Department of Computer Science', 6, NULL, NULL),
(4, '2', 'Bộ môn Mạng và truyền thông', 'Department of Communication Networking', 6, NULL, NULL),
(5, '2', 'Bộ môn Khoa học và Kỹ thuật tính toán', 'Department of Computing Science and Engineering', 6, NULL, NULL),
(6, '1', 'Khoa Công nghệ thông tin', 'Faculty of Information Technology', 18, '__1__2__3__4__5__', NULL),
(7, '2', 'Bộ môn Hệ thống viễn thông', 'Department of Network & Communication Systems', 11, NULL, NULL),
(8, '2', 'Bộ môn Thông tin vô tuyến', 'Department of Wireless Communications', 11, NULL, NULL),
(9, '2', 'Bộ môn Điện tử và Kỹ thuật máy tính', 'Department of Electronics and Computer Engineering', 11, NULL, NULL),
(10, '2', 'Bộ môn Vi cơ điện tử và Vi cơ hệ thống', 'Department of Micro-Electro-Mechanical Systems and Micro Systems', 11, NULL, NULL),
(11, '1', 'Khoa Điện tử - Viễn thông', 'Faculty of Electronics and Telecommunications', 11, '__7__8__5__10__', NULL,),
(12, '3', 'Phòng Đào tạo', 'Division of Academic Affairs', 18, '__11__6__', NULL),
(13, '3', 'Phòng Công tác sinh viên', 'Division of Student Affairs', 18, NULL, NULL, '1'),
(14, '3', 'Phòng KHCN & HTQT', 'Division of Science, Technology and International Relations', 18, NULL, NULL),
(15, '3', 'Phòng Tổ chức - hành chính', 'Division of Human Resources and Administration', 18, NULL, NULL),
(16, '3', 'Phòng Kế hoạch - Tài vụ', 'Division of Planning and Finance', 18, NULL, NULL),
(17, '3', 'Trung tâm Đảm bảo chất lượng', 'Center for Quality Assurance', 18, NULL, NULL),
(18, '0', 'Trường Đại học Công nghệ', 'University of Engineering and Technology', 19, '__11__13__14__12__15__16__17__6__', NULL),
(19, '0', 'Đại học Quốc gia Hà Nội', 'Vietnam National University', 0, '__18__', NULL),
(20, '1', 'Khoa Cơ học kỹ thụât và Tự động hoá', 'Faculty of Engineering Mechanics and Automation', 18, '__21__22__23__24__', 'FEMA'),
(21, '2', 'Bộ môn Thủy khí công nghiệp và môi trường', 'Department of Industrial and Environmental Fluid-Mechanics Engineering', 20, NULL, 'FEMA-DIEFME'),
(22, '2', 'Bộ môn Hàng không vũ trụ', 'Department of Aerospace Engineering', 20, NULL, 'FEMA-DIEFME', '1'),
(23, '2', 'Bộ môn Công nghệ biển và môi trường', 'Department of Marine and Environment Engineering', 20, NULL, 'FEMA-DIEFME'),
(24, '2', 'Bộ môn Công nghệ cơ điện tử', 'Department of Mechatronics Engineering', 20, NULL, 'FEMA-DIEFME', '1'),
(25, '1', 'Khoa Vật lý KT và CN Nanô', 'Faculty of Engineering Physics and Nanotechnology', 18, '__26__27__28__29__', 'FEPN'),
(26, '2', 'Bộ môn Công nghệ quang tử', 'Department of Nanophotonics Technology', 25, NULL, NULL),
(27, '2', 'Bộ môn Vật liệu và linh kiện từ tính nano', 'Department of Nano Magnetic Materials and Devices', 25, NULL, NULL),
(28, '2', 'Bộ môn Vật liệu và linh kiện bán dẫn nano', 'Department of Nano Semiconductor Materials and Devices', 25, NULL, NULL),
(29, '2', 'Bộ môn Công nghệ nano sinh học', 'Department of Nano Biotechnology', 25, NULL, NULL, '1');